// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: LilyGo_T-Panel_Starter

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 182 );
lv_obj_set_y( ui_Label4, 210 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Screen 2");

ui_TabView3 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 50);
lv_obj_set_height( ui_TabView3, 400);
lv_obj_set_width( ui_TabView3, lv_pct(100));
lv_obj_set_x( ui_TabView3, 0 );
lv_obj_set_y( ui_TabView3, -40 );
lv_obj_set_align( ui_TabView3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_TabView3, lv_color_hex(0xF9F2F2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TabView3, 128, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TabView3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_TabPage1 = lv_tabview_add_tab(ui_TabView3, "Page 1");

ui_Label1 = lv_label_create(ui_TabPage1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 2 );
lv_obj_set_y( ui_Label1, 150 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"This is page 1");

ui_Calendar1 = lv_calendar_create(ui_TabPage1);
lv_obj_t *ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
lv_obj_set_width( ui_Calendar1, 230);
lv_obj_set_height( ui_Calendar1, 240);
lv_obj_set_x( ui_Calendar1, 8 );
lv_obj_set_y( ui_Calendar1, -23 );
lv_obj_set_align( ui_Calendar1, LV_ALIGN_CENTER );

ui_TabPage2 = lv_tabview_add_tab(ui_TabView3, "Page 2");

ui_Label5 = lv_label_create(ui_TabPage2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 1 );
lv_obj_set_y( ui_Label5, 153 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"This is page 2");

ui_Keyboard2 = lv_keyboard_create(ui_TabPage2);
lv_obj_set_width( ui_Keyboard2, 300);
lv_obj_set_height( ui_Keyboard2, 120);
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

ui_TabPage3 = lv_tabview_add_tab(ui_TabView3, "Page 3");

ui_Label6 = lv_label_create(ui_TabPage3);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 8 );
lv_obj_set_y( ui_Label6, 150 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"This is page 3");

ui_Colorwheel1 = lv_colorwheel_create(ui_TabPage3,true);
lv_obj_set_width( ui_Colorwheel1, 150);
lv_obj_set_height( ui_Colorwheel1, 150);
lv_obj_set_x( ui_Colorwheel1, 4 );
lv_obj_set_y( ui_Colorwheel1, -16 );
lv_obj_set_align( ui_Colorwheel1, LV_ALIGN_CENTER );

ui_Label8 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -109 );
lv_obj_set_y( ui_Label8, 210 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Swipe here to change screens...");

lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
